### ISSUE TITLE
Make release publishing entirely automatic by automating the "close" and "release" stages of Nexus Repository manager

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#349]
Spent some time trying to get this working but to no avail, here was where I left the job (which belongs in in https://github.com/kwebio/kweb-core/blob/master/.github/workflows/publish-to-maven-central.yml).

```yaml
# Couldn't get this working yet, need to get the SONATYPE_REPOSITORY_ID from output of publish step. For now
# closing and release will need to be manual.
  release:
    name: Close and Release Sonatype staging repository
    runs-on: ubuntu-latest
    needs: [test, publish]
    if: ${{ always() && needs.test.result == 'success' && needs.publish.result == 'success' }}
    steps:
      - name: Release
        uses: nexus-actions/release-nexus-staging-repo@f2b4c7f64ecec2cb0d24349182c1bbeda5c4c056
        with:
          base_url: https://s01.oss.sonatype.org/service/local/
          username: ${{ secrets.OSSRHUSERNAME }}
          password: ${{ secrets.OSSRHPASSWORD }}
          staging_repository_id: no ${{ secrets.SONATYPE_REPOSITORY_ID }}
          description: Closed ${{ github.repository }}#${{ github.run_number }}
          close_only: false
```
