### ISSUE TITLE
Evaluate Github Actions and consider using for C.I instead of Travis-CI

### ISSUE THREAD

**Issue by sanity** [kwebio/kweb-core#70]
Seems that Github Issues is [coming along](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/), meanwhile there have been rumors of the long-term stability of Travis-CI, the free service we currently use.

We should investigate whether a migration over is a good idea, and if-so - do it.

**Comment by alkoclick** [comment]
I may be interested in giving this a go if I have some free time over the next few weeks. Is there anything more to the current CI scripts than [this](https://github.com/kwebio/kweb-core/blob/master/.travis.yml)? If not, I already have some ideas for things that can be done

**Comment by sanity** [comment]
I don't think there is anything aside from the TravisCI config file, let me know if I can assist.

**Comment by alkoclick** [comment]
So, first opinion:

GitHub Actions is a good concept and definitely will be worth the move (eventually). For now, you can do this part of the script:
```
 
language: java
jdk:
  - oraclejdk12
addons:
  chrome: stable

script:
  - ./gradlew build --scan -s -Dsel.jup.default.browser=chrome
  - ./gradlew test --rerun-tasks -Dsel.jup.default.browser=firefox
```

but you cannot do this:
```
notifications:
  email:
    on_failure: always
    on_success: never

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
```
Caching is [currently not supported](https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/30974#M630) though it may be soon. Have you taken a look at [Circle CI](https://circleci.com)? I've been using them for some very complex builds including image generation, caching, and Kubernetes deployments and they have been very nice. They also support Open Source projects. I could implement the current scripts as a CircleCI pipeline instead if you're interested. Alternatively, you could wait out GH Actions
